global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus tự monitor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Monitor cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Monitor Java Servlet app
  - job_name: 'vinfastsystem'
    static_configs:
      - targets: ['vinfastsystem_app:8081']


  # BỎ job 'vinfastsystem' vì không còn HTTP metrics endpoint
  # JMX monitoring sẽ thông qua JConsole/VisualVM kết nối tới port 9999

  # BỎ SQL Server job (nếu không có SQL Server exporter riêng)
  # - job_name: 'sqlserver'
  #   static_configs:
  #     - targets: ['host.docker.internal:1433']
  #   scrape_interval: 30s